name: Build LaTeX Resume and Deploy to GitHub Pages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Compile Resume
        uses: dante-ev/latex-action@latest
        with:
          root_file: resume.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape

      - name: Move PDF to build folder
        run: |
          mv resume.pdf Maaz_Zaidi_Resume.pdf
          git config --global user.name "Maaz Zaidi"
          git config --global user.email "maaz.zaidi2003@gmail.com"
          git add .
          git commit -m '📄🔨 Generate Resume' || echo
          git push

